### ISSUE TITLE
Add support for options when creating new S3 client

### ISSUE THREAD

**Issue by johnparn** [opencomponents/storage-adapters#27]
In order to support a non Amazon S3 compliant object storage, like Riak CS, Minion etc, it is necessary to be able to override the endpoint generated when creating a new client using `new AWS.S3();` in the oc-s3-storage-adapter. The endpoint that is created by default follows the pattern `https://{service}.{region}.amazonaws.com`.

By specifying an options attribute in the S3 configuration of the registry configuration, the options can be used when creating a new client, ie `new AWS.S3(conf.options);`.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property

**Comment by nickbalestra** [comment]
Thanks for this @johnparn, make sense to me.
Would you like to attempt a PR?

**Comment by kmcrawford** [comment]
The code currently does the following where it first sets values from the conf.  I could look for endpoint to override the default AWS endpoint, or accept a new object that could override any AWS value.

Current code:
```
 AWS.config.update({
    accessKeyId: conf.key,
    secretAccessKey: conf.secret,
    region: conf.region,
    httpOptions
  });
  ....
  const getClient = () => new AWS.S3();
```

Current conf:
```
{
  storage: {
    adapter: s3,
    options: {
        key: 'my-key',
        secret: 'my-secret',
        bucket: 'my-bucket',
        region: 'us-east-1',
        path: '//s3.amazonaws.com/my-bucket/',
        componentsDir: 'components'
    }
}
```
Proposed conf:

```
{
  storage: {
    adapter: s3,
    options: {
        bucket: 'my-bucket',
        path: '//s3.amazonaws.com/my-bucket/',
        componentsDir: 'components',
        clientOverride: {
             endpoint: 'http://my-endpoint/',
             accessKeyId: 'myAccessKey',
             secretAccessKey: 'mySecretAccessKey'
            ...
        }
    }
}
```
If clientOverride exists use the following:
const getClient = () => new AWS.S3(conf.clientOverride);

**Comment by johnparn** [comment]
I will make a PR. 

@kmcrawford That is along the lines I thought as well.

**Comment by johnparn** [comment]
Hmm...

I've changed the S3 adapter to override the endpoint settings, but for some reason the endpoint refuses to be overridden. When trying to create a new registry it still tries to connect to s3.amazonaws.com. I would expect it to try to connect to the docker RiakCS at localhost:8080.

After a while a tried to isolate the problem and when connecting straight to the RiakCS using AWS-SDK, using the same configuration settings, it works just fine. Like so:

```
"use strict";
const AWS = require('aws-sdk');

var configuration = {
  verbosity: 0,
  baseUrl: 'http://localhost',
  port: 3333,
  tempDir: './temp/',
  refreshInterval: 600,
  pollingInterval: 5,
  storage: {
    options: {
      key: 'CJP8PH_UOE_9LAGTV1SO',
      secret: 'HP4I5tu3fXKTtAYMT94W7I9rsp5rKa9fkVslpA==',
      bucket: '', // Specified bucket will be used as prefix of the hostname, ie bucket.example.com. Omit for RiakCS
      path: '//localhost:8080/components', 
      componentsDir: 'components',
      signatureVersion: 'v2', // Use v2 for RiakCS
      endpoint: {
        protocol: 'http',
        hostname: 'localhost',
        port: '8080'
      }  
    }    
  },
  env: { name: 'production' }
};


// Defaults
const bucket = (configuration.storage.options.bucket) ? configuration.storage.options.bucket : '';
const sslEnabled = (configuration.storage.options.sslEnabled === false) ? {sslEnabled: false} : {};
const signatureVersion = (configuration.storage.options.signatureVersion) ? {signatureVersion: configuration.storage.options.signatureVersion} : {};
const httpOptions = { timeout: configuration.storage.options.timeout || 10000 };
if (configuration.storage.options.agentProxy) {
  httpOptions.agent = configuration.storage.options.agentProxy;
}

// Setup AWS config
let awsConfig = new AWS.Config({
  accessKeyId: configuration.storage.options.key,
  secretAccessKey: configuration.storage.options.secret,
  ...signatureVersion,
  ...sslEnabled,
  ...httpOptions
});

// Setup endpoint
if (configuration.storage.options.endpoint) {
  let awsEndpoint = new AWS.Endpoint(configuration.storage.options.endpoint.hostname);
  awsEndpoint.port = configuration.storage.options.endpoint.port;
  awsEndpoint.protocol = configuration.storage.options.endpoint.protocol;

  awsConfig.update({
    endpoint: awsEndpoint
  });
}


let client = new AWS.S3(awsConfig);
client.listObjects({
  Bucket: bucket
},
(err, data) => {
  if (err) {
    console.log('Error', err);
    return;
  }
  console.log('Result', data);
});
```

Running this yields a result (but there are no content in place):

```
Result { Contents: [], CommonPrefixes: [] }
```
 
Changing the S3 adapter to use the corresponding configuration section as the file above will not work. Here's a gist with files: https://gist.github.com/johnparn/4f352c524409eff0c22c6c5dfc53804b

**Comment by nickbalestra** [comment]
@johnparn I think we can close this?

**Comment by johnparn** [comment]
Closing as this is now implemented.
