### ISSUE TITLE
[DX-366] Wrong protocol for oc-client.min.js when requested in registry web interface

### ISSUE THREAD

**Issue by johnparn** [opencomponents/storage-adapters#34]
If the registry is communicating with the storage with plain http instead of https, the request for `oc-client.min.js` is still using the _https_ protocol. 

Of course, the storage should use a SSL/TLS encryption when exposed publicly, but in this case I'm running a registry locally. The registry runs on http://localhost:3333 and the storage on http://localhost:8080. When accessing the registry in the browser (http://localhost:3333/) there is a request in the browser for `https://localhost:8080/bucket/components/oc-client/0.42.16/src/oc-client.min.js`. Notice the https protocol. As the storage isn't exposed with https locally that yields an error. 

The problem seems to be in `/oc/src/registry/domain/repository.js`, where the protocol _https_ is hardcoded in `getComponentPath`, `getStaticClientPathand` and `getStaticClientMapPath`.

The configuration used for the registry looks like this:

```
let configuration = {
  verbosity: 5,
  baseUrl: 'http://localhost:3333',
  port: 3333,
  tempDir: './temp/',
  refreshInterval: 600,
  pollingInterval: 5,
  storage: {
    adapter: riak,
    options: {
      key: '...',
      secret: '...',
      bucket: 'foo',
      region: 'us-east-1',
      componentsDir: 'components',
      signatureVersion: 'v2', 
      sslEnabled: false,
      path: '//localhost:8080/foo/', 
      s3ForcePathStyle: true, 
      debug: true, 
      endpoint: {
        protocol: 'http',
        hostname: 'localhost',
        port: '8080'
      }  
    }    
  },
  env: { name: 'production' }
};
```

**Comment by johnparn** [comment]
Some further info - it is the _path_-attribute in the config that is used for that particular request.

**Comment by nickbalestra** [comment]
Solved with https://github.com/opentable/oc/pull/813
