### ISSUE TITLE
Extract azure helper functions

### ISSUE THREAD

**Issue by pbazydlo** [opencomponents/storage-adapters#63]
Extract azure helper functions into separate file. This would allow us to test them separately from the adapter itself.

**Comment by nickbalestra** [comment]
Hey @pbazydlo, being going through issues to do some grooming and noticed this is being sitting here since a while. Was wondering if you want or plan to work on this? or Should we close it?

**Comment by pbazydlo** [comment]
Realistically I won't be able to work on this for a while - closing.
